version: '3.1'
services:

        db:
                image: mongo
                restart: always
                networks:
                        - db_network  # for API reqs
                environment:
                        MONGO_INITDB_ROOT_USERNAME: $DB_USERNAME 
                        MONGO_INITDB_ROOT_PASSWORD: $DB_PASSWORD
                        MONGO_INITDB_DATABASE: $MONGO_INITDB_DATABASE
                volumes:
                    - database:/data/db

        db-interface:
                image: mongo-express
                restart: always
                environment:
                        ME_CONFIG_MONGODB_ADMINUSERNAME: $DB_USERNAME
                        ME_CONFIG_MONGODB_ADMINPASSWORD: $DB_PASSWORD
                        ME_CONFIG_SITE_BASEURL: /db_interface/
                        ME_CONFIG_MONGODB_SERVER: db
                networks:
                        - db_network  # access db
                        - web_network  # access the interface
                depends_on:
                        - db

        app:
               build: .
               image: pk13055/ldap
               restart: always
               volumes:
                       - .:/app
               environment:
                       PORT: 8080
                       DEBUG: $DEBUG
                       SECRET_KEY: $SECRET_KEY
                       DATABASE_URL: $DATABASE_URL
               depends_on:
                       - db
               networks:
                       - db_network  # for data fetching/upload
                       - web_network  # for web API

        nginx:
               image: nginx:latest
               ports:
                       - 8000:80
               volumes:
                       - ./config/nginx:/etc/nginx/conf.d/
               depends_on:
                       - app
                       - db-interface
               networks:
                       - web_network


networks:
        db_network:
                driver: bridge
        web_network:
                driver: bridge

volumes:
        database:

